name: myenv  # 환경 이름
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8  # 원하는 Python 버전
  - asgiref==3.8.1
  - Django==5.1.2
  - django-cors-headers==4.6.0
  - djangorestframework==3.15.2
  - python-decouple==3.8
  - sqlparse==0.5.1
  - typing_extensions==4.12.2
  - torch==1.6.0
  - torchvision==0.7.0
  - torchaudio==0.6.0
  - jupyterlab==3.4.0
  - opencv-python  # conda에서 사용할 수 있는 버전으로 설치
  - matplotlib
  - scikit-learn
  - tqdm
  - pycocotools
  - tensorboard